story = "This one time at Burning Man, I built a 60 foot long, 40 foot high {user_value1}. And the next day I rode my {user_value2} by a crew taking wedding pictures, but my skirt was down and my ass made a bullseye in their wedding photo. So I {user_value3} in a {user_value4} parade from my camp to the Man for the burn. Just at the moment I got tired of riding my {user_value5} bike through the {user_value6} playa, I found a park bench with white writing all over the {user_value7}, so I sat down and {user_value8} the copy of The Brothers Karamozov chained to it. And then I met a {user_value9} who told me she’d gotten married earlier in the day and her vows were “0100111000101000101”. And we {user_value10} a gigantic copper dragon rolling by, chased by hundreds of {user_value11}, so I {user_value12} and found myself in deep playa at a {user_value13} album release party hosted by {user_value1}. ".format("late", "my dog", "my wife") // use string values for user input
print(story)
# if __name__ == "__main__":
#     print(var)

    user_value1 = user_input("Please Enter a noun:")
print(user_value1)
 user_value2 = user_input("Please Enter a noun:")
print(user_value2)
 user_value3 = user_input("Please Enter a past tense verb:")
print(user_value3)
 user_value4 = user_input("Please Enter an adjective:")
print(user_value4)
 user_value5 = user_input("Please Enter an adjective:")
print(user_value5)
 user_value6 = user_input("Please Enter an adjective:")
print(user_value6)
 user_value7 = user_input("Please Enter a plural noun:")
print(user_value7)
 user_value8 = user_input("Please Enter a past tense verb:")
print(user_value8)
 user_value9 = user_input("Please Enter a noun:")
print(user_value9)
 user_value10 = user_input("Please Enter a past tense verb:")
print(user_value10)
 user_value11 = user_input("Please Enter a plural noun:")
print(user_value11)
 user_value12 = user_input("Please Enter a past tense verb:")
print(user_value12)
user_value13 = user_input("Please Enter a band name:")
print(user_value13)
 user_value14 = user_input("Please Enter a famous person's name:")
print(user_value14)

